version: '3.7'

services:
    cw-project-radar:
        env_file:
          - .env.prod
        build:
            context: .
            dockerfile: Dockerfile_node
        image: cw-radar-node:latest
        container_name: cw-radar-node
        restart: always
        init: true
        ports:
            - 80:8080
        networks:
            cw-radar-nw:
        depends_on:
            - mongo
        command: node server/server.js

    mongo:
        build:
            context: .
            dockerfile: Dockerfile_mongo
        image: cw-radar-mongo:latest
        container_name: cw-radar-mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=cw-project-radar
        volumes:
            - dbdata:/data/db
        ports:
            - 27017:27017
        networks:
            cw-radar-nw:

volumes:
    dbdata:
        name: cw-radar-data

networks:
    cw-radar-nw:
        name: cw-radar
